<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { activateAssessmentRule, createAssessmentRule, listAssessmentRules, type AssessmentRule, type RuleStatus, type RuleType } from '@/shared/api'
import { useAuthStore } from '@/stores/auth'
const authStore = useAuthStore(); const loading = ref(false); const rows = ref<AssessmentRule[]>([]); const createVisible = ref(false); const submitting = ref(false)
const filters = reactive({ ruleType: '' as RuleType | '', status: '' as RuleStatus | '' })
const form = reactive({ ruleType: 'COMPLETENESS' as RuleType, versionCode: '', ruleName: '', ruleContent: '{\n  "dimensions": [],\n  "levels": []\n}' })
const canManage = computed(() => authStore.hasRole('ADMIN'))
async function load(): Promise<void> { loading.value = true; try { rows.value = await listAssessmentRules({ ruleType: filters.ruleType || undefined, status: filters.status || undefined }) } catch (error) { ElMessage.error(error instanceof Error ? error.message : '评分规则加载失败') } finally { loading.value = false } }
async function submit(): Promise<void> { submitting.value = true; try { const ruleContent = JSON.parse(form.ruleContent) as Record<string, unknown>; await createAssessmentRule({ ruleType: form.ruleType, versionCode: form.versionCode, ruleName: form.ruleName, ruleContent }); ElMessage.success('规则草稿已创建，服务端已校验权重、阈值和 SHA-256'); createVisible.value = false; await load() } catch (error) { ElMessage.error(error instanceof Error ? error.message : '规则草稿创建失败') } finally { submitting.value = false } }
async function activate(rule: AssessmentRule): Promise<void> { await ElMessageBox.confirm(`激活 ${rule.versionCode} 后内容不可编辑，同类型旧规则将退役，是否继续？`, '确认激活规则', { type: 'warning' }); try { const result = await activateAssessmentRule(rule.ruleId); ElMessage.success(`规则已激活，${result.staleAssessmentCount} 条当前评分已标记过期`); await load() } catch (error) { ElMessage.error(error instanceof Error ? error.message : '规则激活失败') } }
function statusType(status: RuleStatus): 'success' | 'info' | 'warning' { if (status === 'ACTIVE') return 'success'; if (status === 'DRAFT') return 'warning'; return 'info' }
onMounted(load)
</script>
<template>
  <section class="rules-page"><header class="page-header"><div><p class="eyebrow">Assessment Rules</p><h1>评分规则版本</h1><p>规则状态遵循 DRAFT → ACTIVE → RETIRED，激活规则不可原地编辑。</p></div><el-button v-if="canManage" type="primary" @click="createVisible = true">创建规则草稿</el-button></header>
    <el-card shadow="never"><el-form inline><el-form-item label="规则类型"><el-select v-model="filters.ruleType" clearable style="width: 170px" @change="load"><el-option label="数据完整度" value="COMPLETENESS" /><el-option label="安全风险" value="RISK" /><el-option label="更新优先级" value="RENEWAL" /></el-select></el-form-item><el-form-item label="状态"><el-select v-model="filters.status" clearable style="width: 140px" @change="load"><el-option label="草稿" value="DRAFT" /><el-option label="已激活" value="ACTIVE" /><el-option label="已退役" value="RETIRED" /></el-select></el-form-item></el-form></el-card>
    <el-card shadow="never"><el-table v-loading="loading" :data="rows" row-key="ruleId"><el-table-column prop="ruleType" label="类型" width="150" /><el-table-column prop="versionCode" label="版本" min-width="160" /><el-table-column prop="ruleName" label="名称" min-width="220" /><el-table-column label="状态" width="100"><template #default="scope"><el-tag :type="statusType(scope.row.status)">{{ scope.row.status }}</el-tag></template></el-table-column><el-table-column prop="checksum" label="规范化 SHA-256" min-width="360" show-overflow-tooltip /><el-table-column prop="activatedAt" label="激活时间" min-width="190" /><el-table-column v-if="canManage" label="操作" width="110" fixed="right"><template #default="scope"><el-button v-if="scope.row.status === 'DRAFT'" link type="primary" @click="activate(scope.row)">激活</el-button></template></el-table-column></el-table></el-card>
    <el-dialog v-model="createVisible" title="创建评分规则草稿" width="760px"><el-form label-width="110px"><el-form-item label="规则类型"><el-select v-model="form.ruleType" style="width: 220px"><el-option label="数据完整度" value="COMPLETENESS" /><el-option label="安全风险" value="RISK" /><el-option label="更新优先级" value="RENEWAL" /></el-select></el-form-item><el-form-item label="版本编码"><el-input v-model="form.versionCode" placeholder="例如 RISK-V2" /></el-form-item><el-form-item label="规则名称"><el-input v-model="form.ruleName" /></el-form-item><el-form-item label="规则 JSON"><el-input v-model="form.ruleContent" type="textarea" :rows="18" spellcheck="false" /></el-form-item></el-form><template #footer><el-button @click="createVisible = false">取消</el-button><el-button type="primary" :loading="submitting" @click="submit">创建草稿</el-button></template></el-dialog>
  </section>
</template>
<style scoped lang="scss">.rules-page { display: grid; gap: 18px; }.page-header { display: flex; justify-content: space-between; align-items: flex-start; gap: 20px; }.page-header h1 { margin: 4px 0; font-size: 30px; }.page-header p { margin: 0; color: #667085; }.eyebrow { color: #287a6a !important; font-size: 12px; font-weight: 800; letter-spacing: .12em; text-transform: uppercase; }</style>
