<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { calculateBuildingAssessment, getBuildingAssessmentHistory, getCurrentBuildingAssessment, type AssessmentHistoryItem, type BuildingCurrentAssessment, type RenewalPrioritySummary, type ScoreDimension } from '@/shared/api'
import { useAuthStore } from '@/stores/auth'
const route = useRoute(); const authStore = useAuthStore(); const buildingId = computed(() => String(route.params.buildingId || '')); const loading = ref(false); const calculating = ref(false); const current = ref<BuildingCurrentAssessment | null>(null); const history = ref<AssessmentHistoryItem[]>([])
const canCalculate = computed(() => authStore.hasAnyRole(['ADMIN', 'GOVERNMENT_MANAGER', 'COMMUNITY_MANAGER']))
const formalPriority = computed<RenewalPrioritySummary | undefined>(() => current.value?.renewalPriorities.find((item) => item.rankingScopeKey === 'ALL') || current.value?.renewalPriorities[0])
const allDimensions = computed<ScoreDimension[]>(() => [...(current.value?.completeness?.dimensionScores || []), ...(current.value?.risk?.dimensionScores || [])])
const isStale = computed(() => current.value?.freshness === 'STALE')
const freshnessText = computed(() => current.value?.freshness === 'STALE' ? 'STALE（存在过期评分）' : current.value?.freshness || '--')
async function load(): Promise<void> { if (!buildingId.value) return; loading.value = true; try { const [assessment, historyPage] = await Promise.all([getCurrentBuildingAssessment(buildingId.value), getBuildingAssessmentHistory(buildingId.value, { page: 0, size: 50 })]); current.value = assessment; history.value = historyPage.content } catch (error) { ElMessage.error(error instanceof Error ? error.message : '楼栋评分加载失败') } finally { loading.value = false } }
async function calculate(force: boolean): Promise<void> { if (!buildingId.value) return; if (force) await ElMessageBox.confirm('强制重算会保留新历史结果，是否继续？', '确认强制重算', { type: 'warning', confirmButtonText: '继续重算' }); calculating.value = true; try { const result = await calculateBuildingAssessment(buildingId.value, { force, rankingScopes: ['COMMUNITY', 'REGION', 'ALL'] }); ElMessage.success(result.reused ? '输入与规则未变化，已复用当前结果' : '评分计算完成'); await load() } catch (error) { ElMessage.error(error instanceof Error ? error.message : '评分计算失败') } finally { calculating.value = false } }
function scoreText(value?: number): string { return value == null ? '--' : Number(value).toFixed(2) }
function percent(value?: number): string { return value == null ? '--' : `${Math.round(Number(value) * 100)}%` }
function riskTag(level?: string): 'success' | 'warning' | 'danger' | 'info' { if (level === 'VERY_HIGH' || level === 'HIGH') return 'danger'; if (level === 'MEDIUM') return 'warning'; if (level === 'LOW') return 'success'; return 'info' }
onMounted(load)
</script>
<template>
  <section v-loading="loading" class="assessment-page">
    <header class="page-header"><div><p class="eyebrow">Building Assessment</p><h1>{{ current?.buildingName || '楼栋评分详情' }}</h1><p>{{ current?.communityName }} · {{ current?.buildingCode }}</p></div><div v-if="canCalculate" class="actions"><el-button :loading="calculating" @click="calculate(false)">计算或复用</el-button><el-button type="primary" :loading="calculating" @click="calculate(true)">强制重算</el-button></div></header>
    <el-alert v-if="current" :title="current.disclaimer" type="warning" :closable="false" show-icon />
    <el-empty v-if="current?.freshness === 'NO_RESULT'" description="当前楼栋尚无正式评分结果" />
    <el-alert v-if="isStale" title="当前展示结果包含过期评分，请重算后再用于优先级研判" type="error" :closable="false" show-icon />
    <div v-if="current && current.freshness !== 'NO_RESULT'" class="score-grid">
      <el-card shadow="never" class="score-card"><span>数据完整度</span><strong>{{ scoreText(current?.completeness?.completenessScore) }}</strong><el-tag effect="plain">{{ current?.completeness?.completenessLevel || '无结果' }}</el-tag><small>越高表示资料越完整</small></el-card>
      <el-card shadow="never" class="score-card"><span>安全风险筛查</span><strong>{{ scoreText(current?.risk?.riskScore) }}</strong><el-tag :type="riskTag(current?.risk?.riskLevel)">{{ current?.risk?.riskLevel || '无结果' }}</el-tag><small>越高表示风险特征越明显，不是安全概率</small></el-card>
      <el-card shadow="never" class="score-card"><span>判断置信度</span><strong>{{ scoreText(current?.risk?.confidenceScore) }}</strong><el-tag :type="current?.risk?.confidenceScore && current.risk.confidenceScore < 60 ? 'warning' : 'success'">{{ current?.risk?.confidenceLevel || '无结果' }}</el-tag><small>越高表示当前证据越充分可靠</small></el-card>
      <el-card shadow="never" class="score-card"><span>城市更新优先级</span><strong>{{ scoreText(formalPriority?.priorityScore) }}</strong><el-tag :type="formalPriority?.priorityLevel === 'P1' ? 'danger' : 'info'">{{ formalPriority?.priorityLevel || '无结果' }}</el-tag><small>正式排名：{{ formalPriority?.ranking || '--' }} · {{ formalPriority?.rankingScopeKey || '--' }}</small></el-card>
    </div>
    <div v-if="current?.risk" class="detail-grid">
      <el-card shadow="never"><template #header><strong>维度子分与权重</strong></template><el-table :data="allDimensions" size="small"><el-table-column prop="label" label="维度" min-width="170" /><el-table-column prop="score" label="子分" width="90" /><el-table-column label="权重" width="90"><template #default="scope">{{ percent(scope.row.weight) }}</template></el-table-column><el-table-column prop="contribution" label="贡献" width="90" /><el-table-column prop="evidenceCount" label="证据数" width="90" /></el-table></el-card>
      <el-card shadow="never"><template #header><strong>主要因素与排除证据</strong></template><el-timeline><el-timeline-item v-for="factor in current.risk.topFactors" :key="`${factor.factorCode}-${factor.sourceId || factor.label}`" :type="factor.direction === 'EXCLUDED' ? 'info' : 'danger'"><strong>{{ factor.label }}</strong><p>方向：{{ factor.direction }} · 影响：{{ scoreText(factor.effect) }}</p></el-timeline-item></el-timeline><el-empty v-if="!current.risk.topFactors.length" description="暂无主要因素" :image-size="72" /><el-divider>排除证据</el-divider><el-tag v-for="item in current.risk.excludedEvidence" :key="item.sourceId || item.reason" type="info" effect="plain" class="evidence-tag">{{ item.reason }}</el-tag><p v-if="!current.risk.excludedEvidence.length" class="muted">没有被排除的人工智能证据。</p></el-card>
      <el-card shadow="never"><template #header><strong>缺失资料与建议措施</strong></template><h4>缺失资料</h4><ul><li v-for="item in current.completeness?.missingItems || []" :key="item">{{ item }}</li><li v-for="item in current.risk.missingData" :key="`risk-${item}`">{{ item }}</li></ul><h4>建议措施</h4><ul><li v-for="item in current.completeness?.suggestions || []" :key="item">{{ item }}</li><li v-for="item in current.risk.recommendations" :key="`risk-${item}`">{{ item }}</li><li v-for="item in formalPriority?.recommendations || []" :key="`priority-${item}`">{{ item }}</li></ul></el-card>
      <el-card shadow="never"><template #header><strong>规则版本与输入摘要</strong></template><el-descriptions :column="1" border size="small"><el-descriptions-item label="结果状态">{{ freshnessText }}</el-descriptions-item><el-descriptions-item label="完整度规则">{{ current.completeness?.ruleVersion }}</el-descriptions-item><el-descriptions-item label="风险规则">{{ current.risk.ruleVersion }}</el-descriptions-item><el-descriptions-item label="优先级规则">{{ formalPriority?.ruleVersion }}</el-descriptions-item><el-descriptions-item label="引擎版本">{{ current.risk.engineVersion }}</el-descriptions-item><el-descriptions-item label="风险输入摘要">{{ current.risk.inputChecksum }}</el-descriptions-item><el-descriptions-item label="证据可靠性">{{ scoreText(current.risk.evidenceReliabilityScore) }}</el-descriptions-item></el-descriptions></el-card>
    </div>
    <el-card shadow="never"><template #header><strong>评分历史</strong></template><el-table :data="history" size="small"><el-table-column prop="calculatedAt" label="计算时间" min-width="190" /><el-table-column prop="assessmentType" label="类型" width="130" /><el-table-column prop="score" label="分数" width="90" /><el-table-column prop="secondaryScore" label="置信度" width="90" /><el-table-column prop="level" label="等级" width="100" /><el-table-column prop="status" label="状态" width="110" /><el-table-column prop="ruleVersion" label="规则版本" min-width="150" /><el-table-column prop="triggerType" label="触发方式" width="120" /></el-table></el-card>
  </section>
</template>
<style scoped lang="scss">
.assessment-page { display: grid; gap: 20px; }.page-header { display: flex; justify-content: space-between; align-items: flex-start; gap: 20px; }.page-header h1 { margin: 4px 0; font-size: 30px; }.page-header p { margin: 0; color: #667085; }.eyebrow { color: #287a6a !important; font-size: 12px; font-weight: 800; letter-spacing: .12em; text-transform: uppercase; }.actions { display: flex; gap: 10px; }.score-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 14px; }.score-card :deep(.el-card__body) { display: grid; gap: 10px; }.score-card span { color: #475467; }.score-card strong { font-size: 34px; line-height: 1; }.score-card small, .muted { color: #667085; }.detail-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px; }ul { margin: 8px 0 18px; padding-left: 20px; color: #475467; line-height: 1.8; }.evidence-tag { margin: 0 8px 8px 0; white-space: normal; height: auto; padding: 6px 9px; }@media (max-width: 1100px) { .score-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } }@media (max-width: 760px) { .page-header { display: grid; } .score-grid, .detail-grid { grid-template-columns: 1fr; } }
</style>
