<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.urbansafe</groupId>
        <artifactId>urban-safe-priority-server</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>client</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.urbansafe</groupId>
            <artifactId>model</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-feign-client</id>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <inputSpec>${project.parent.basedir}/model/src/main/resources/openapi-interface.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <library>spring-cloud</library>
                            <invokerPackage>org.urbansafe.priority.client.invoker</invokerPackage>
                            <apiPackage>org.urbansafe.priority.client.feign</apiPackage>
                            <modelPackage>org.urbansafe.priority.model.dto</modelPackage>
                            <generateApis>true</generateApis>
                            <generateModels>false</generateModels>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateApiTests>false</generateApiTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateModelTests>false</generateModelTests>
                            <skipIfSpecIsUnchanged>true</skipIfSpecIsUnchanged>
                            <inlineSchemaNameMappings>
                                <inlineSchemaNameMapping>createAiInference_201_response=AiInferenceSuccessResponse</inlineSchemaNameMapping>
                            </inlineSchemaNameMappings>
                            <configOptions>
                                <configPackage>org.urbansafe.priority.client.config</configPackage>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <requestMappingMode>none</requestMappingMode>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <serializationLibrary>jackson</serializationLibrary>
                                <openApiNullable>false</openApiNullable>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-ai-governance-feign-client</id>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <inputSpec>${project.parent.basedir}/model/src/main/resources/ai-governance/openapi-ai-governance.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <library>spring-cloud</library>
                            <invokerPackage>org.urbansafe.priority.client.invoker</invokerPackage>
                            <apiPackage>org.urbansafe.priority.client.feign</apiPackage>
                            <modelPackage>org.urbansafe.priority.model.dto</modelPackage>
                            <generateApis>true</generateApis>
                            <generateModels>false</generateModels>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateApiTests>false</generateApiTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateModelTests>false</generateModelTests>
                            <skipIfSpecIsUnchanged>true</skipIfSpecIsUnchanged>
                            <configOptions>
                                <configPackage>org.urbansafe.priority.client.config</configPackage>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <requestMappingMode>none</requestMappingMode>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <serializationLibrary>jackson</serializationLibrary>
                                <openApiNullable>false</openApiNullable>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-spatial-feign-client</id>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <inputSpec>${project.parent.basedir}/model/src/main/resources/spatial/openapi-spatial.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <library>spring-cloud</library>
                            <invokerPackage>org.urbansafe.priority.client.invoker</invokerPackage>
                            <apiPackage>org.urbansafe.priority.client.feign</apiPackage>
                            <modelPackage>org.urbansafe.priority.model.dto</modelPackage>
                            <generateApis>true</generateApis>
                            <generateModels>false</generateModels>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateApiTests>false</generateApiTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateModelTests>false</generateModelTests>
                            <skipIfSpecIsUnchanged>true</skipIfSpecIsUnchanged>
                            <configOptions>
                                <configPackage>org.urbansafe.priority.client.config</configPackage>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <requestMappingMode>none</requestMappingMode>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <serializationLibrary>jackson</serializationLibrary>
                                <openApiNullable>false</openApiNullable>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>